export const plainurl = "yuuire.com";

export const meta = {
  author: "yuuire",
  name: "yuuire",
  description: " ",
  shortdesc: "❄️🍵💜🌿",
  plainurl: plainurl,
  sponsor: "https://github.com/sponsors/yuuire",
  keywords: [
    "privacy",
    "developer",
    "designer",
    "self-taught heart surgeon",
    "musician",
    "guitarist",
    "vocalist",
    "voice actor",
    "youtuber",
    "streamer",
    "rapper",
    "journalist",
    "lawyer",
    "i love apples",
    "tea addict",
    "money",
    "robux",
    "windows",
    "advice",
    "macos",
    "linux",
    "markdown",
    "security",
    "website",
    "anonymity",
    "guide",
    "privacy-online",
    "opsec",
    "anonymization",
    "privacy protection",
    "privacy tools",
    "privacy guides",
    "tor",
    "security guides",
    "data breach",
    "metadata",
    "smart devices",
    "yuuire"
  ],
  lastfm_api: "dfaf6aaa44371d7f5e020b930b5cb515",
  discord: "https://discord.gg/hJM9gSQ4PB",
};